// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: display_esp32_nicegest

#ifndef _DISPLAY_ESP32_UI_H
#define _DISPLAY_ESP32_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

// SCREEN: ui_Screen
void ui_screen_init(void);
extern lv_obj_t *ui_Screen;

extern lv_obj_t *ui_base_lbMain;
extern lv_obj_t *ui_base_lbSysInfo;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif