// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: display_esp32

#include "../ui.h"

void ui_screen_init(void) {
    ui_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    /* base */
    ui_base_lbMain = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_base_lbMain, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_base_lbMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_base_lbMain, 0);
    lv_obj_set_y(ui_base_lbMain, 0);
    lv_obj_set_align(ui_base_lbMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_base_lbMain, "");
    lv_obj_set_style_text_color(ui_base_lbMain, lv_color_hex(0x02098F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_base_lbMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_base_lbMain, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_base_lbMain, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_clear_flag(ui_base_lbMain, LV_OBJ_FLAG_HIDDEN);
    
    ui_base_lbSysInfo = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_base_lbSysInfo, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_base_lbSysInfo, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_base_lbSysInfo, 10); //-225;
    lv_obj_set_y(ui_base_lbSysInfo, 5); //-124;
    lv_obj_set_align(ui_base_lbSysInfo, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_base_lbSysInfo, "v1.0");
    lv_obj_set_style_text_color(ui_base_lbSysInfo, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_base_lbSysInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_base_lbSysInfo, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);    
    lv_obj_clear_flag(ui_base_lbSysInfo, LV_OBJ_FLAG_HIDDEN);

}